spring.application.name=auth


server.port = 8082

spring.datasource.url=jdbc:postgresql://localhost:5432/airline_auth_db
spring.datasource.username=postgres
spring.datasource.password=post30@MARQ46
spring.datasource.driver-class-name=org.postgresql.Driver