spring.application.name=auth


server.port = 8082

spring.datasource.url=jdbc:postgresql://localhost:5432/airline_auth_db
spring.datasource.username=postgres
spring.datasource.password=post30@MARQ46
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=Qm9SaG9PcGFzQ2NwT0R5Q1JlTm9UZXN0U2VjcmV0MTIz

# 15 Minutes
jwt.access-token-expiration=900000

# 7 Days
jwt.refresh-token-expiration=604800000